version: 1.0.{build}
install:
- nuget restore letsencrypt-win-simple.sln
- cp -R packages letsencrypt-win-simple
configuration: Release
build:
  project: letsencrypt-win-simple.sln
  verbosity: minimal

test_script:
 - pushd letsencrypt-tests\bin\release\
 - ..\..\..\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -returntargetcode -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\mstest.exe" -targetargs:"/testcontainer:.\letsencrypt-tests.dll" -output:".\coverage.xml" -filter:"+[letsencrypt*]* -[letsencrypt-tests*]*"

after_test:
- ps: |
    If ($Env:APPVEYOR_REPO_BRANCH -eq "master")
    {
      SET PATH=C:\Python34;C:\Python34\Scripts;%PATH%
      pip install codecov
      codecov -f ".\coverage.xml" -t %CodeCovUploadToken%
    }

after_build:
- ps: |
    If ($Env:APPVEYOR_REPO_BRANCH -eq "master")
    {
      pushd letsencrypt-win-simple\bin\release\
      7z a letsencrypt-win-simple.zip letsencryptcli.exe
      7z a letsencrypt-win-simple.zip letsencryptcli.exe.config
      7z a letsencrypt-win-simple.zip letsencryptcli.pdb
      7z a letsencrypt-win-simple.zip Web_Config.xml
      popd
    }

artifacts:
- path: letsencrypt-win-simple\bin\release\letsencrypt-win-simple.zip
  name: letsencrypt-win-simple